source "https://rubygems.org"

ruby "2.1.3"

gem "rails", "4.2.0.beta2"
gem "pg"
gem "sass-rails", "~> 5.0.0.beta1"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.0.0"
gem "jquery-rails"
gem "rails-html-sanitizer", "~> 1.0"
gem "unicorn"
gem "simple_form"
gem "omniauth-facebook"
gem "twilio-ruby"
gem "skylight"

group :development do
  gem "better_errors"
  gem "meta_request"
  gem "quiet_assets"
end

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0.0.beta2"
  gem "spring"
  gem "spring-commands-rspec"
  gem "rspec-rails"
  gem "shoulda-matchers"
  gem "capybara"
  gem "capybara-screenshot"
  gem "dotenv-rails"
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "faker"
  gem "poltergeist"
  gem "awesome_print"
  gem "hirb"
  gem "pry-rails"
  gem "pry-nav"
  gem "pry-stack_explorer"
  gem "pry-theme"
  gem "rubocop"
end