---
default: &default
  cloud_name: shillcock
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false

development:
  <<: *default

test:
  <<: *default

production: &default
  <<: *default
  static_image_support: true

