default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  database: family_development

test:
  <<: *default
  database: family_test

#production:
#  <<: *default
#  database: family_production
#  username: family
#  password: <%= ENV['FAMILY_DATABASE_PASSWORD'] %>
