default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

